SET GLOBAL event_scheduler = ON;

CREATE EVENT AutoDeleteUnregisteredUsers
ON SCHEDULE AT CURRENT_TIMESTAMP + INTERVAL 1 DAY 
ON COMPLETION PRESERVE
DO 
	DELETE FROM accounts WHERE created < DATE_SUB(NOW(), INTERVAL 10 DAY) && confirmed = 0;
    
CREATE EVENT AutoDeleteOldVeriCodes
ON SCHEDULE AT CURRENT_TIMESTAMP + INTERVAL 1 DAY 
ON COMPLETION PRESERVE
DO 
	DELETE FROM verification_codes WHERE created < DATE_SUB(NOW(), INTERVAL 10 DAY);
    
CREATE EVENT AutoDeleteLoginKeys
ON SCHEDULE AT CURRENT_TIMESTAMP + INTERVAL 1 DAY 
ON COMPLETION PRESERVE
DO 
	DELETE FROM logged_in WHERE created < DATE_SUB(NOW(), INTERVAL 30 DAY);
