SET GLOBAL event_scheduler = ON;
SHOW PROCESSLIST;
SHOW EVENTS;
/*DROP EVENT AutoDeleteLoginKeys;*/

CREATE EVENT AutoDeleteUnregisteredUsers
ON SCHEDULE EVERY 1 DAY
STARTS CURRENT_TIMESTAMP
DO 
	DELETE FROM ebdb.accounts WHERE created < DATE_SUB(NOW(), INTERVAL 10 DAY) && confirmed = 0;
    
CREATE EVENT AutoDeleteOldVeriCodes
ON SCHEDULE EVERY 1 DAY
STARTS CURRENT_TIMESTAMP
DO 
	DELETE FROM ebdb.verification_codes WHERE created < DATE_SUB(NOW(), INTERVAL 10 DAY);
    
CREATE EVENT AutoDeleteLoginKeys
ON SCHEDULE EVERY 1 DAY
STARTS CURRENT_TIMESTAMP
DO 
	DELETE FROM ebdb.logged_in WHERE created < DATE_SUB(NOW(), INTERVAL 30 DAY);
